language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 4.0

before_script:
  - npm install -g bower
  - bower install
  - sudo node test/js/server.js ../../ 80 &
  - sleep 5

script: phantomjs test/index.html "http://localhost:80/test/index.html"

after_success:
  - coveralls
