language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 4.0

before_script:
  - npm install -g bower
  - bower install

script: phantomjs test/index.html

after_success:
  - coveralls
